import Ember from 'ember';
var controller;

controller = Ember.Controller.extend({
  appController: Ember.inject.controller('application'),
  notify: Ember.inject.service('notify'),
  fileObj: '',
  imageSource: '',
  roleTypes: ['ADMIN', 'NARRATOR', 'CREATOR'],
  deleteDialog: false,
  actions: {
    askDelete: function() {
      return this.set('deleteDialog', true);
    },
    removeDeleteDialog: function() {
      return this.set('deleteDialog', false);
    },
    
    "delete": function() {
      var that;
      that = this;
      return this.model.destroyRecord().then(function() {
        that.set('deleteDialog', false);
        return that.transitionToRoute("users.index");
      });
    },

    saveUser: function() {
      var self;
      self = this;
      return self.get('model').save().then(function() {
        self.get('notify').info("Success !!");
        return self.transitionToRoute("users.index");
      });
    },
    goBack: function() {
      return this.transitionToRoute("users.index");
    },
    updateRecord: function(file) {
      var fileReader, self;
      this.set('fileObj', file);
      self = this;
      fileReader = new FileReader();
      fileReader.readAsDataURL(file.blob);
      return fileReader.onload = function(e) {
        return self.set('imageSource', e.target.result);
      };
    }
  }
});

export default controller;

// ---
// generated by coffee-script 1.9.2