require 'yaml'

FAYE_CONFIG = YAML.load_file(File.expand_path('../config.yml', __FILE__))

namespace :faye do
  desc "Start"
  task :start do
    `rackup config.ru -s thin -E production -p 9292 -D -o "#{FAYE_CONFIG['mount_ip']}"`
  end

  desc "TODO"
  task :stop do
    `kill -9 \`lsof -w -n -i tcp:9292 -t\``
  end
end
